version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant_ramayana
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage_docker:/qdrant/storage:z
    restart: always

networks:
  default:
    name: ramayana_network
